
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        image: rameshkumarverma/password-generator
        ports:
        - containerPort: 80
