apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-2048-game-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: a-2048-game
  template:
    metadata:
      labels:
        app: a-2048-game
    spec:
      containers:
      - name: a-2048-game
        image: rameshkumarverma/2048-game
        ports:
        - containerPort: 80
