apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-game-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: blackjack-game
  template:
    metadata:
      labels:
        app: blackjack-game
    spec:
      containers:
      - name: blackjack-game
        image: rameshkumarverma/blackjack-game
        ports:
        - containerPort: 80
