
apiVersion: apps/v1
kind: Deployment
metadata:
  name: typing-speed-test-website-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: typing-speed-test-website
  template:
    metadata:
      labels:
        app: typing-speed-test-website
    spec:
      containers:
      - name: typing-speed-test-website
        image: rameshkumarverma/typing-speed-test-website
        ports:
        - containerPort: 80
