
apiVersion: apps/v1
kind: Deployment
metadata:
  name: height-converter-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: height-converter
  template:
    metadata:
      labels:
        app: height-converter
    spec:
      containers:
      - name: height-converter
        image: rameshkumarverma/height-converter
        ports:
        - containerPort: 80
