
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-code-generator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: qr-code-generator
  template:
    metadata:
      labels:
        app: qr-code-generator
    spec:
      containers:
      - name: qr-code-generator
        image: rameshkumarverma/qr-code-generator
        ports:
        - containerPort: 80
