
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-calculator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: tip-calculator
  template:
    metadata:
      labels:
        app: tip-calculator
    spec:
      containers:
      - name: tip-calculator
        image: rameshkumarverma/tip-calculator
        ports:
        - containerPort: 80
