
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-search-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: movie-search-app
  template:
    metadata:
      labels:
        app: movie-search-app
    spec:
      containers:
      - name: movie-search-app
        image: rameshkumarverma/movie-search-app
        ports:
        - containerPort: 80
