
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-generator-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: quote-generator
  template:
    metadata:
      labels:
        app: quote-generator
    spec:
      containers:
      - name: quote-generator
        image: rameshkumarverma/quote-generator
        ports:
        - containerPort: 80
