apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-portfolio-website-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: basic-portfolio-website
  template:
    metadata:
      labels:
        app: basic-portfolio-website
    spec:
      containers:
      - name: basic-portfolio-website
        image: rameshkumarverma/basic-portfolio-website
        ports:
        - containerPort: 80
