
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-solver-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: sudoku-solver
  template:
    metadata:
      labels:
        app: sudoku-solver
    spec:
      containers:
      - name: sudoku-solver
        image: rameshkumarverma/sudoku-solver
        ports:
        - containerPort: 80
